language: python
python:
  - "2.7"
install:
  - createdb misago_0_5
  - pip install -e .[postgresql]
  - pip install python-coveralls
script:
  - coverage erase
  - coverage run --source=misago manage.py test  --settings=misago.settings.testing --nologcapture misago
  - coverage report --show-missing
after_success:
  - coveralls
